const fs = require('fs');
const raw = [
["Abort","İptal etmek/Durdurmak","Genel",2,"The mission was aborted due to technical failure."],
["Abrupt","Ani/Beklenmedik","Genel",2,"An abrupt change in temperature was recorded."],
["Abundance","Bolluk/Çokluk","Biyoloji",1,"The abundance of fish species has declined."],
["Accessible","Erişilebilir","Genel",1,"Clean water should be accessible to all."],
["Accuracy","Doğruluk/Kesinlik","Fen",1,"The accuracy of the measurement was confirmed."],
["Acidic","Asidik","Kimya",1,"Lemon juice is acidic with a low pH value."],
["Acknowledge","Kabul etmek/Onaylamak","Genel",2,"The researcher acknowledged the limitations."],
["Acquisition","Edinim/Kazanım","Genel",2,"Language acquisition begins in early childhood."],
["Adjacent","Bitişik/Komşu","Genel",2,"The two habitats are adjacent to each other."],
["Adverse","Olumsuz/Ters","Genel",2,"Adverse effects of the drug were minimal."],
["Advocate","Savunmak/Desteklemek","Genel",2,"Scientists advocate for renewable energy."],
["Aggregate","Toplam/Küme","Fen",2,"The aggregate data showed a positive trend."],
["Albeit","Her ne kadar/Olsa da","Genel",3,"The results, albeit preliminary, are encouraging."],
["Allocate","Tahsis etmek/Ayırmak","Genel",2,"Funds were allocated for climate research."],
["Ambiguous","Belirsiz/Çift anlamlı","Genel",2,"The results were ambiguous and hard to interpret."],
["Analogy","Benzetme/Analoji","Genel",2,"The analogy between the brain and a computer is common."],
["Anatomy","Anatomi","Biyoloji",1,"Human anatomy is studied in medical school."],
["Anomaly","Anomali/Sapma","Fen",2,"An anomaly in the data required further investigation."],
["Apparatus","Araç/Cihaz","Fen",1,"The experimental apparatus was carefully calibrated."],
["Arbitrary","Keyfi/Rastgele","Genel",2,"The selection criteria were not arbitrary."],
["Array","Dizi/Sıra","Fen",2,"An array of sensors was deployed across the field."],
["Assemble","Birleştirmek/Montaj yapmak","Fen",1,"The components were assembled in the laboratory."],
["Autonomous","Özerk/Bağımsız","Fen",2,"The robot operates in an autonomous mode."],
["Axis","Eksen","Fizik",1,"The Earth tilts on its axis at 23.5 degrees."],
["Bacteria","Bakteri","Biyoloji",1,"Bacteria are single-celled microorganisms."],
["Bias","Önyargı/Sapma","Genel",2,"Confirmation bias can affect research outcomes."],
["Biodegradable","Biyolojik olarak parçalanabilir","Kimya",2,"Biodegradable materials decompose naturally."],
["Breakthrough","Atılım/Çığır açan gelişme","Genel",1,"A breakthrough in cancer research was announced."],
["Buffer","Tampon","Kimya",2,"A buffer solution resists changes in pH."],
["Bulk","Yığın/Hacim","Fen",1,"The bulk of the evidence supports the theory."],
["Calibrate","Kalibre etmek","Fen",2,"The instruments must be calibrated before use."],
["Carbon","Karbon","Kimya",1,"Carbon is the basis of organic chemistry."],
["Cell","Hücre","Biyoloji",1,"The cell is the basic unit of life."],
["Ceramic","Seramik","Fen",2,"Ceramic materials withstand high temperatures."],
["Channel","Kanal","Fen",1,"Ion channels regulate cell membrane potential."],
["Circumference","Çevre/Çevre uzunluğu","Fizik",1,"The circumference of the Earth is about 40,000 km."],
["Coexist","Birlikte var olmak","Biyoloji",2,"Different species coexist in the same habitat."],
["Cognitive","Bilişsel","Biyoloji",2,"Cognitive functions decline with age."],
["Cohesion","Bağdaşım/Yapışma","Fizik",2,"Cohesion between water molecules creates surface tension."],
["Collapse","Çökmek/Çöküş","Genel",1,"The bridge collapsed under excessive weight."],
["Colony","Koloni","Biyoloji",1,"A colony of bacteria grew on the agar plate."],
["Combustion","Yanma","Kimya",1,"Combustion of fossil fuels releases CO2."],
["Complement","Tamamlamak","Genel",2,"The two methods complement each other."],
["Compression","Sıkıştırma","Fizik",2,"Compression of gas increases its temperature."],
["Concur","Aynı fikirde olmak","Genel",3,"Most experts concur with the findings."],
["Condensation","Yoğuşma","Kimya",1,"Condensation forms water droplets on cold surfaces."],
["Configuration","Yapılandırma/Düzenleme","Fen",2,"The electronic configuration determines reactivity."],
["Congenital","Doğuştan","Biyoloji",2,"The condition is congenital and present from birth."],
["Conjunction","Bağlaç/Birleşme","Genel",2,"The treatment works in conjunction with therapy."],
["Consensus","Uzlaşı/Fikir birliği","Genel",2,"There is scientific consensus on climate change."],
["Contaminant","Kirletici madde","Kimya",1,"Contaminants in the water were identified."],
["Contingent","Bağlı/Koşullu","Genel",3,"Success is contingent upon proper methodology."],
["Contradictory","Çelişkili","Genel",2,"The findings were contradictory to expectations."],
["Controversy","Tartışma/Çekişme","Genel",2,"The study sparked controversy in the field."],
["Conventional","Geleneksel/Alışılmış","Genel",1,"Conventional methods were replaced by new technology."],
["Converge","Yakınsamak","Fizik",2,"The two rivers converge at this point."],
["Core","Çekirdek/Öz","Fen",1,"The core of the Earth is extremely hot."],
["Correlate","İlişkilendirmek","Fen",2,"Smoking correlates with lung cancer risk."],
["Criteria","Ölçüt/Kriter","Genel",1,"The selection criteria were clearly defined."],
["Cumulative","Kümülatif/Birikimli","Genel",2,"The cumulative effect of pollution is devastating."],
["Curriculum","Müfredat","Genel",1,"Science is part of the school curriculum."],
["Cylinder","Silindir","Fizik",1,"Gas was collected in a graduated cylinder."],
["Debris","Enkaz/Kalıntı","Fen",1,"Space debris orbits the Earth."],
["Deficiency","Eksiklik/Yetersizlik","Biyoloji",1,"Iron deficiency causes anemia."],
["Density","Yoğunluk","Fizik",1,"The density of water is 1 gram per cubic centimeter."],
["Depict","Betimlemek/Tasvir etmek","Genel",2,"The diagram depicts the water cycle."],
["Deposit","Birikim/Tortu","Fen",1,"Mineral deposits were found beneath the surface."],
["Designate","Belirlemek/Tayin etmek","Genel",2,"The area was designated as a nature reserve."],
["Detrimental","Zararlı","Genel",2,"Pollution is detrimental to human health."],
["Diagnosis","Teşhis/Tanı","Biyoloji",1,"Early diagnosis improves survival rates."],
["Diameter","Çap","Fizik",1,"The diameter of the cell is about 10 micrometers."],
["Diffuse","Yayılmak/Dağılmak","Fizik",2,"Gases diffuse from high to low concentration."],
["Dilute","Seyreltmek","Kimya",1,"The acid was diluted with distilled water."],
["Dimension","Boyut","Fizik",1,"The object has three dimensions."],
["Disperse","Dağıtmak/Saçmak","Fen",2,"Seeds are dispersed by wind and animals."],
["Displacement","Yer değiştirme","Fizik",1,"Displacement measures the change in position."],
["Doctrine","Doktrin/Öğreti","Genel",3,"The doctrine of evolution is well established."],
["Domain","Alan/Saha","Fen",2,"Molecular biology is a growing research domain."],
["Dominant","Baskın","Biyoloji",1,"The dominant gene determines the phenotype."],
["Dose","Doz","Biyoloji",1,"The correct dose of medicine must be administered."],
["Draft","Taslak","Genel",1,"The first draft of the paper was submitted."],
["Drought","Kuraklık","Fen",1,"Drought conditions threaten agriculture."],
["Durable","Dayanıklı","Fen",1,"The material is lightweight but durable."],
["Dynamic","Dinamik/Hareketli","Fizik",1,"Ocean currents are dynamic and constantly changing."],
["Ecology","Ekoloji","Biyoloji",1,"Ecology studies the relationships between organisms."],
["Efficiency","Verimlilik","Fen",1,"Energy efficiency reduces fuel consumption."],
["Elastic","Elastik/Esnek","Fizik",1,"Rubber is a highly elastic material."],
["Electrode","Elektrot","Kimya",2,"Electrodes conduct electricity in a battery."],
["Elevation","Yükseklik/Rakım","Fen",1,"Air pressure decreases with elevation."],
["Embryo","Embriyo","Biyoloji",1,"The embryo develops into a fetus."],
["Emission","Emisyon/Salınım","Fen",1,"Carbon emissions must be reduced globally."],
["Empirical","Ampirik/Deneysel","Fen",2,"The theory is based on empirical evidence."],
["Encompass","Kapsamak/İçine almak","Genel",2,"The study encompasses a wide range of topics."],
["Endanger","Tehlikeye atmak","Biyoloji",1,"Pollution endangers marine wildlife."],
["Epidemic","Salgın","Biyoloji",1,"The epidemic spread across several countries."],
["Erosion","Erozyon/Aşınma","Fen",1,"Soil erosion is caused by wind and water."],
["Ethical","Etik/Ahlaki","Genel",2,"Ethical considerations guide animal testing."],
["Excavate","Kazmak/Çıkarmak","Fen",2,"Fossils were excavated from the site."],
];
const existing = JSON.parse(fs.readFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json','utf8'));
const startId = existing.length + 1;
const words = raw.map((r, i) => ({
  id: startId + i, word_en: r[0], word_tr: r[1], category: r[2], difficulty: r[3], example_sentence: r[4]
}));
const all = [...existing, ...words];
// Copy to final location
fs.writeFileSync('/Users/fatihbaygul/Desktop/english/src/data/words.json', JSON.stringify(all, null, 2));
fs.writeFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json', JSON.stringify(all, null, 2));
console.log(`Part 5: ${words.length} new. FINAL TOTAL: ${all.length} words.`);
