const fs = require('fs');
const raw = [
["Exceed","Aşmak/Geçmek","Genel",2,"The temperature exceeded 40 degrees Celsius."],
["Exclude","Hariç tutmak","Genel",2,"The study excluded participants under 18."],
["Exhibit","Sergilemek/Göstermek","Genel",2,"The patient exhibited symptoms of infection."],
["Expand","Genişlemek/Büyümek","Fizik",1,"Metals expand when heated."],
["Explicit","Açık/Net","Genel",2,"The instructions were explicit and clear."],
["Exploit","İstismar etmek/Yararlanmak","Genel",2,"Industries exploit natural resources unsustainably."],
["Expose","Maruz bırakmak","Fen",1,"Prolonged exposure to UV rays damages skin cells."],
["Extract","Çıkarmak/Özütlemek","Kimya",1,"DNA is extracted from blood samples for analysis."],
["Feasible","Uygulanabilir/Mümkün","Genel",2,"Solar energy is a feasible alternative to fossil fuels."],
["Fluctuate","Dalgalanmak","Fen",2,"Temperatures fluctuate throughout the day."],
["Forecast","Tahmin etmek/Öngörmek","Fen",2,"Models forecast rising sea levels by 2050."],
["Formulate","Formüle etmek","Fen",2,"The team formulated a new hypothesis."],
["Fragment","Parça/Parçalamak","Fen",1,"The rock fragmented under high pressure."],
["Friction","Sürtünme","Fizik",1,"Friction generates heat between surfaces."],
["Function","İşlev/Çalışmak","Genel",1,"The liver functions as a detoxification organ."],
["Fundamental","Temel","Genel",1,"DNA is fundamental to all living organisms."],
["Generate","Üretmek/Oluşturmak","Fen",1,"Wind turbines generate renewable energy."],
["Genetic","Genetik","Biyoloji",1,"Genetic factors influence disease susceptibility."],
["Glacier","Buzul","Fen",2,"Glaciers are melting at an alarming rate."],
["Gradual","Aşamalı/Kademeli","Genel",1,"Evolution is a gradual process."],
["Habitat","Yaşam alanı","Biyoloji",1,"Deforestation destroys natural habitats."],
["Hazardous","Tehlikeli/Zararlı","Fen",2,"Hazardous chemicals must be handled with care."],
["Hence","Bu nedenle","Genel",2,"The sample was contaminated, hence the results were invalid."],
["Hinder","Engellemek","Genel",2,"Lack of funding hinders scientific progress."],
["Hypothesis","Hipotez/Varsayım","Fen",1,"The hypothesis was tested through experiments."],
["Identical","Aynı/Özdeş","Genel",1,"The two DNA sequences are virtually identical."],
["Identify","Tanımlamak/Belirlemek","Genel",1,"Researchers identified a new species of frog."],
["Immune","Bağışık","Biyoloji",1,"The immune system protects the body from pathogens."],
["Impact","Etki/Darbe","Genel",1,"Human activity has a significant impact on the environment."],
["Implement","Uygulamak","Genel",2,"New safety measures were implemented."],
["Imply","İma etmek","Genel",2,"The data implies a correlation between variables."],
["Impose","Dayatmak/Empoze etmek","Genel",2,"Regulations impose limits on carbon emissions."],
["Inadequate","Yetersiz","Genel",2,"Inadequate nutrition leads to growth disorders."],
["Incline","Eğilim/Eğim","Fizik",1,"The ball rolled down the incline."],
["Incorporate","Dahil etmek/Bünyesine katmak","Genel",2,"The design incorporates new safety features."],
["Indicate","Göstermek/Belirtmek","Genel",1,"Results indicate a positive trend."],
["Induce","Neden olmak/Uyarmak","Fen",2,"Electric current can induce a magnetic field."],
["Inevitable","Kaçınılmaz","Genel",2,"Climate change is an inevitable consequence of emissions."],
["Infectious","Bulaşıcı","Biyoloji",1,"Viruses cause infectious diseases."],
["Infer","Çıkarım yapmak","Genel",2,"We can infer the age of rocks from their layers."],
["Infinite","Sonsuz","Fizik",2,"The universe may be infinite in size."],
["Influence","Etkilemek/Etki","Genel",1,"Gravity influences the motion of planets."],
["Ingredient","İçerik/Bileşen","Kimya",1,"The key ingredient in the reaction is a catalyst."],
["Inhabit","Yaşamak/İkamet etmek","Biyoloji",1,"Many species inhabit tropical rainforests."],
["Inherent","Doğasında olan/Yapısal","Genel",2,"Risk is inherent in all scientific experiments."],
["Inhibit","Engellemek/Baskılamak","Biyoloji",2,"The drug inhibits tumor growth."],
["Initial","Başlangıç/İlk","Genel",1,"The initial results were promising."],
["Inject","Enjekte etmek","Biyoloji",1,"The vaccine was injected into the patient."],
["Innovation","Yenilik/Buluş","Genel",1,"Technological innovation drives economic growth."],
["Insight","İçgörü/Kavrayış","Genel",2,"The study provides valuable insights into behavior."],
["Inspect","İncelemek/Denetlemek","Genel",1,"The specimens were inspected under a microscope."],
["Integrate","Bütünleştirmek","Genel",2,"The model integrates data from multiple sources."],
["Intense","Yoğun/Şiddetli","Genel",1,"Intense heat can cause metal to melt."],
["Interact","Etkileşmek","Fen",1,"Molecules interact through chemical bonds."],
["Intermediate","Ara/Orta","Kimya",2,"An intermediate product forms during the reaction."],
["Internal","İç/Dahili","Genel",1,"The internal organs were examined carefully."],
["Interpret","Yorumlamak","Genel",2,"Scientists interpret data to form conclusions."],
["Intervene","Müdahale etmek","Genel",2,"Medical professionals intervened to save the patient."],
["Investigate","Araştırmak","Fen",1,"The team investigated the cause of the outbreak."],
["Isolate","Yalıtmak/Ayırmak","Fen",1,"The virus was isolated in the laboratory."],
["Isotope","İzotop","Kimya",2,"Carbon-14 is a radioactive isotope."],
["Justify","Haklı çıkarmak","Genel",2,"The results justify further investigation."],
["Kinetic","Kinetik/Hareket","Fizik",2,"Kinetic energy increases with velocity."],
["Label","Etiketlemek","Genel",1,"Each sample was carefully labeled."],
["Layer","Katman/Tabaka","Fen",1,"The ozone layer protects Earth from UV radiation."],
["Lethal","Öldürücü/Ölümcül","Biyoloji",2,"The venom of this snake is lethal."],
["Likewise","Aynı şekilde/Benzer biçimde","Genel",2,"Temperature affects density; pressure likewise plays a role."],
["Magnitude","Büyüklük/Ölçek","Fizik",2,"The magnitude of the earthquake was 7.2."],
["Maintain","Sürdürmek/Korumak","Genel",1,"The body maintains a constant internal temperature."],
["Mammal","Memeli","Biyoloji",1,"Whales are marine mammals."],
["Manifest","Göstermek/Ortaya çıkmak","Genel",2,"The disease manifests itself through skin lesions."],
["Manipulate","Manipüle etmek/Yönlendirmek","Fen",2,"Scientists manipulate genes to study their function."],
["Mature","Olgunlaşmak","Biyoloji",1,"The fruit matures over several weeks."],
["Mechanism","Mekanizma","Fen",1,"The mechanism of enzyme action is well understood."],
["Medium","Ortam/Araç","Fen",1,"Sound travels faster through a liquid medium."],
["Membrane","Zar/Membran","Biyoloji",1,"The cell membrane controls what enters the cell."],
["Metabolism","Metabolizma","Biyoloji",2,"Metabolism converts food into energy."],
["Microscopic","Mikroskobik","Biyoloji",1,"Bacteria are microscopic organisms."],
["Migrate","Göç etmek","Biyoloji",1,"Birds migrate south during winter."],
["Mineral","Mineral/Maden","Fen",1,"Bones contain calcium and other minerals."],
["Minimize","En aza indirmek","Genel",1,"Safety measures minimize the risk of accidents."],
["Mitigate","Hafifletmek/Azaltmak","Genel",2,"Trees help mitigate the effects of climate change."],
["Modify","Değiştirmek/Uyarlamak","Fen",1,"The design was modified to improve efficiency."],
["Moisture","Nem","Fen",1,"Moisture in the air affects weather patterns."],
["Molecular","Moleküler","Kimya",2,"The molecular structure determines chemical properties."],
["Monitor","İzlemek/Gözlemlemek","Fen",1,"Sensors monitor air quality continuously."],
["Morphology","Morfoloji/Biçimbilim","Biyoloji",3,"The morphology of the cell was examined."],
["Mutual","Karşılıklı","Genel",2,"The relationship is of mutual benefit."],
["Navigate","Yol bulmak/Seyrüsefer","Genel",2,"Animals navigate using magnetic fields."],
["Negligible","İhmal edilebilir","Fen",2,"The error was negligible and could be ignored."],
["Neutral","Nötr/Yansız","Kimya",1,"Pure water has a neutral pH of 7."],
["Nevertheless","Yine de/Buna rağmen","Genel",2,"The data was limited; nevertheless, the results were significant."],
["Niche","Niş/Ekolojik alan","Biyoloji",2,"Each species fills a unique ecological niche."],
["Norm","Norm/Standart","Genel",1,"Deviations from the norm require investigation."],
["Notable","Dikkat çekici/Kayda değer","Genel",2,"A notable increase in temperature was recorded."],
["Notion","Kavram/Düşünce","Genel",2,"The notion that the Earth is flat has been disproved."],
["Nucleus","Çekirdek","Biyoloji",1,"The nucleus contains DNA."],
["Nutrient","Besin/Besin maddesi","Biyoloji",1,"Plants absorb nutrients from the soil."],
["Obtain","Elde etmek","Genel",1,"Results were obtained from controlled experiments."],
["Obvious","Açık/Bariz","Genel",1,"The damage to the coral reef was obvious."],
["Occupy","İşgal etmek/Kaplamak","Genel",2,"Forests occupy large areas of the continent."],
["Occur","Meydana gelmek","Genel",1,"Earthquakes occur along tectonic plate boundaries."],
];
const existing = JSON.parse(fs.readFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_part1.json','utf8'));
const startId = existing.length + 1;
const words = raw.map((r, i) => ({
  id: startId + i, word_en: r[0], word_tr: r[1], category: r[2], difficulty: r[3], example_sentence: r[4]
}));
const all = [...existing, ...words];
fs.writeFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json', JSON.stringify(all, null, 2));
console.log(`Part 2: ${words.length} new. Total: ${all.length} words.`);
