const fs = require('fs');
const raw = [
["Offspring","Yavru/Döl","Biyoloji",1,"The offspring inherit traits from both parents."],
["Ongoing","Devam eden/Süregelen","Genel",1,"Ongoing research aims to find a cure."],
["Optimal","En uygun/Optimum","Fen",2,"The optimal temperature for growth is 37°C."],
["Orbit","Yörünge/Yörüngede dönmek","Fizik",1,"The Earth orbits the Sun once a year."],
["Organic","Organik","Kimya",1,"Organic compounds contain carbon atoms."],
["Organism","Organizma/Canlı","Biyoloji",1,"Microorganisms are the smallest living organisms."],
["Orient","Yönlendirmek","Genel",2,"The compass needle orients itself toward north."],
["Oscillate","Salınmak","Fizik",2,"The pendulum oscillates back and forth."],
["Outcome","Sonuç","Genel",1,"The outcome of the experiment was unexpected."],
["Output","Çıktı/Verim","Fen",1,"The output of the generator was measured."],
["Overlap","Örtüşmek/Çakışmak","Genel",2,"The habitats of these species overlap."],
["Overwhelm","Bunaltmak/Alt etmek","Genel",2,"The immune system was overwhelmed by the infection."],
["Oxide","Oksit","Kimya",1,"Iron oxide is commonly known as rust."],
["Parasite","Parazit/Asalak","Biyoloji",1,"Parasites depend on their host for survival."],
["Particle","Parçacık","Fizik",1,"Subatomic particles make up atoms."],
["Peculiar","Tuhaf/Kendine özgü","Genel",2,"The species has peculiar behavioral traits."],
["Penetrate","Nüfuz etmek/Girmek","Fen",2,"X-rays can penetrate soft tissue."],
["Perceive","Algılamak","Genel",2,"Humans perceive light through photoreceptors."],
["Persist","Devam etmek/Sürmek","Genel",2,"The drought persisted for several months."],
["Pertinent","İlgili/Uygun","Genel",3,"Only pertinent data was included."],
["Phenomena","Olgu/Fenomen","Fen",2,"Natural phenomena include earthquakes and volcanoes."],
["Photosynthesis","Fotosentez","Biyoloji",1,"Photosynthesis converts carbon dioxide into glucose."],
["Pollutant","Kirletici","Fen",1,"Factories release pollutants into the atmosphere."],
["Portion","Kısım/Pay","Genel",1,"A large portion of the forest was destroyed."],
["Pose","Oluşturmak/Ortaya koymak","Genel",2,"Pollution poses a threat to marine life."],
["Possess","Sahip olmak","Genel",2,"Some organisms possess the ability to regenerate."],
["Potential","Potansiyel/Olası","Genel",1,"The compound has potential medical applications."],
["Precede","Önce gelmek/Öncelemek","Genel",2,"A planning phase preceded the experiment."],
["Precise","Kesin/Hassas","Genel",1,"Precise measurements are essential in chemistry."],
["Predator","Yırtıcı/Avcı","Biyoloji",1,"Predators control prey populations."],
["Predict","Tahmin etmek","Genel",1,"Models predict future climate conditions."],
["Predominant","Baskın/Hakim","Genel",2,"The predominant species in the area is oak."],
["Preliminary","Ön/Başlangıç","Genel",2,"Preliminary results suggest a positive outcome."],
["Preserve","Korumak/Muhafaza etmek","Biyoloji",1,"We must preserve natural ecosystems."],
["Prevail","Geçerli olmak/Hâkim olmak","Genel",2,"Dry conditions prevail in desert regions."],
["Prevalent","Yaygın","Genel",2,"The disease is more prevalent in tropical areas."],
["Previous","Önceki","Genel",1,"Previous studies confirmed these findings."],
["Primarily","Esas olarak/Başlıca","Genel",1,"The diet consists primarily of plants."],
["Primitive","İlkel","Biyoloji",2,"Primitive organisms lacked complex cell structures."],
["Principal","Başlıca/Temel","Genel",1,"The principal cause of extinction is habitat loss."],
["Principle","İlke/Prensip","Fen",1,"The principle of conservation of energy is universal."],
["Probe","Sonda/Araştırmak","Fen",2,"The space probe collected data from Mars."],
["Procedure","Prosedür/Yöntem","Fen",1,"The surgical procedure lasted three hours."],
["Proceed","Devam etmek/İlerlemek","Genel",1,"The reaction proceeds at room temperature."],
["Process","Süreç/İşlem","Genel",1,"Photosynthesis is a complex biological process."],
["Profound","Derin/Köklü","Genel",2,"The discovery had a profound impact on medicine."],
["Prohibit","Yasaklamak","Genel",2,"The use of harmful pesticides is prohibited."],
["Prominent","Belirgin/Öne çıkan","Genel",2,"A prominent feature of the landscape."],
["Promote","Teşvik etmek/Desteklemek","Genel",1,"Sunlight promotes vitamin D production."],
["Proportion","Oran/Orantı","Fen",1,"A large proportion of the ice cap has melted."],
["Prospect","Olasılık/Beklenti","Genel",2,"The prospect of finding life on Mars excites scientists."],
["Protein","Protein","Biyoloji",1,"Proteins are essential for cell repair."],
["Protocol","Protokol/Prosedür","Fen",2,"Safety protocols were strictly followed."],
["Prove","Kanıtlamak","Genel",1,"The theory was proved through rigorous testing."],
["Provide","Sağlamak/Temin etmek","Genel",1,"Trees provide oxygen for the atmosphere."],
["Proximity","Yakınlık","Genel",2,"Proximity to the equator affects climate."],
["Pump","Pompalamak/Pompa","Fizik",1,"The heart pumps blood throughout the body."],
["Purify","Arındırmak/Saflaştırmak","Kimya",2,"Filters purify drinking water."],
["Quantify","Nicelendirmek","Fen",2,"It is difficult to quantify biodiversity loss."],
["Radiation","Radyasyon/Işınım","Fizik",1,"Ultraviolet radiation causes skin damage."],
["Range","Aralık/Çeşit","Genel",1,"A wide range of species live in this habitat."],
["Ratio","Oran","Fen",1,"The ratio of hydrogen to oxygen in water is 2:1."],
["React","Tepkime vermek","Kimya",1,"Acids react with bases to form salts."],
["Recover","İyileşmek/Geri kazanmak","Genel",1,"The ecosystem took decades to recover."],
["Reduce","Azaltmak/İndirgemek","Genel",1,"Recycling reduces waste significantly."],
["Refine","İyileştirmek/Arıtmak","Fen",2,"The method was refined over several trials."],
["Reflect","Yansıtmak","Fizik",1,"Mirrors reflect light in a predictable way."],
["Region","Bölge","Genel",1,"Tropical regions receive the most sunlight."],
["Register","Kaydetmek","Genel",2,"The instrument registered a slight increase."],
["Regulate","Düzenlemek","Biyoloji",1,"Hormones regulate body functions."],
["Reinforce","Güçlendirmek/Pekiştirmek","Genel",2,"The findings reinforced the original hypothesis."],
["Reject","Reddetmek","Genel",1,"The hypothesis was rejected based on the evidence."],
["Relevant","İlgili/Uygun","Genel",1,"Only relevant variables were considered."],
["Reliable","Güvenilir","Genel",1,"The method produces reliable results."],
["Reluctant","İsteksiz","Genel",2,"Scientists were reluctant to accept the theory."],
["Rely","Güvenmek/Bel bağlamak","Genel",1,"Many communities rely on groundwater for drinking."],
["Remainder","Kalan/Geri kalan","Genel",2,"The remainder of the sample was discarded."],
["Remedy","Çare/Tedavi","Biyoloji",2,"Scientists are searching for a remedy for the disease."],
["Remote","Uzak/Uzaktan","Genel",1,"Samples were collected from remote areas."],
["Remove","Kaldırmak/Çıkarmak","Genel",1,"Filters remove impurities from water."],
["Render","Kılmak/Yapmak","Genel",2,"Pollution rendered the water undrinkable."],
["Renew","Yenilemek","Fen",1,"Renewable energy sources include solar and wind."],
["Replicate","Kopyalamak/Çoğaltmak","Biyoloji",2,"DNA replicates during cell division."],
["Reproduce","Üremek/Çoğalmak","Biyoloji",1,"Bacteria reproduce by binary fission."],
["Require","Gerektirmek","Genel",1,"Plants require sunlight for photosynthesis."],
["Reside","İkamet etmek/Bulunmak","Genel",2,"Beneficial bacteria reside in the human gut."],
["Residue","Kalıntı/Artık","Kimya",2,"Chemical residues were found in the soil."],
["Resist","Direnmek/Dayanmak","Genel",1,"Some bacteria resist antibiotics."],
["Resolve","Çözmek/Karara bağlamak","Genel",2,"The issue was resolved through further analysis."],
["Restore","Geri kazandırmak/Onarmak","Genel",2,"Efforts to restore the wetland habitat have begun."],
["Restrict","Kısıtlamak/Sınırlamak","Genel",1,"Access to the laboratory is restricted."],
["Retain","Tutmak/Muhafaza etmek","Genel",2,"The soil retains moisture after rainfall."],
["Reveal","Ortaya çıkarmak/Göstermek","Genel",1,"The study revealed a strong correlation."],
["Reverse","Tersine çevirmek/Ters","Genel",2,"The process can be reversed under certain conditions."],
["Revise","Gözden geçirmek/Düzeltmek","Genel",2,"The theory was revised based on new data."],
["Rigid","Katı/Sert","Fizik",2,"The structure must be rigid enough to withstand pressure."],
["Robust","Güçlü/Sağlam","Genel",2,"The organism has a robust immune system."],
["Rotate","Dönmek/Döndürmek","Fizik",1,"The Earth rotates on its axis every 24 hours."],
["Rupture","Yırtılmak/Kopma","Fen",2,"The membrane ruptured under excessive pressure."],
];
const existing = JSON.parse(fs.readFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json','utf8'));
const startId = existing.length + 1;
const words = raw.map((r, i) => ({
  id: startId + i, word_en: r[0], word_tr: r[1], category: r[2], difficulty: r[3], example_sentence: r[4]
}));
const all = [...existing, ...words];
fs.writeFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json', JSON.stringify(all, null, 2));
console.log(`Part 3: ${words.length} new. Total: ${all.length} words.`);
