const fs = require('fs');
const raw = [
["Saturate","Doyurmak","Kimya",2,"The solution was fully saturated with salt."],
["Scale","Ölçek","Fen",1,"The experiment was conducted on a large scale."],
["Scarce","Kıt/Az","Genel",2,"Fresh water is scarce in arid regions."],
["Scatter","Saçmak/Dağılmak","Fizik",2,"Light scatters when passing through a prism."],
["Scope","Kapsam","Genel",2,"The scope of the study was limited to mammals."],
["Secrete","Salgılamak","Biyoloji",2,"Glands secrete hormones into the bloodstream."],
["Sector","Sektör/Kesim","Genel",1,"The energy sector contributes to emissions."],
["Sediment","Tortu/Çökelti","Fen",1,"Sediments accumulate at the bottom of rivers."],
["Segment","Bölüm/Parça","Genel",1,"Each segment of DNA carries genetic information."],
["Sequence","Dizi/Sıra","Biyoloji",1,"The DNA sequence was analyzed."],
["Severe","Şiddetli/Ciddi","Genel",1,"Severe droughts affect crop production."],
["Shed","Dökmek/Yaymak","Genel",2,"The study sheds light on the mechanism."],
["Shift","Değişim/Kaymak","Genel",1,"A shift in climate patterns was observed."],
["Shrink","Küçülmek/Büzülmek","Genel",1,"Glaciers shrink due to rising temperatures."],
["Significant","Önemli/Anlamlı","Genel",1,"The difference was statistically significant."],
["Simulate","Simüle etmek","Fen",2,"Computers simulate complex weather patterns."],
["Simultaneously","Aynı anda","Genel",2,"Two reactions occurred simultaneously."],
["Sketch","Taslak/Çizmek","Genel",1,"The researcher sketched the experimental setup."],
["Sole","Tek/Yegâne","Genel",2,"The sole purpose of the study was to test safety."],
["Soluble","Çözünür","Kimya",1,"Sugar is soluble in water."],
["Solution","Çözelti/Çözüm","Kimya",1,"The chemical was dissolved in an aqueous solution."],
["Sophisticated","Gelişmiş/Karmaşık","Genel",2,"The lab uses sophisticated equipment."],
["Source","Kaynak","Genel",1,"The sun is the primary source of energy."],
["Span","Süre/Kapsamak","Genel",2,"The study spanned a period of five years."],
["Speculate","Spekülasyon yapmak","Genel",2,"Scientists speculate about the origin of life."],
["Sphere","Küre","Fizik",1,"The Earth is roughly spherical in shape."],
["Spontaneous","Kendiliğinden","Kimya",2,"Spontaneous reactions occur without external energy."],
["Stable","Kararlı/Dengeli","Kimya",1,"Noble gases are chemically stable."],
["Stem","Kök/Gövde","Biyoloji",1,"Stem cells can develop into different cell types."],
["Stimulate","Uyarmak/Teşvik etmek","Biyoloji",2,"Hormones stimulate growth and development."],
["Strain","Tür/Gerinim","Biyoloji",2,"A new strain of the virus was discovered."],
["Stress","Stres/Gerilim","Fen",1,"Thermal stress can cause materials to crack."],
["Structure","Yapı","Fen",1,"The structure of DNA is a double helix."],
["Subject","Konu/Denek","Genel",1,"The subjects were observed for three months."],
["Subsequent","Sonraki/Müteakip","Genel",2,"Subsequent experiments confirmed the results."],
["Substance","Madde","Kimya",1,"Water is the most common substance on Earth."],
["Substitute","İkame etmek/Yerine koymak","Genel",2,"Artificial sweeteners substitute for sugar."],
["Subtle","İnce/Belirsiz","Genel",2,"Subtle changes in temperature affect migration."],
["Successive","Ardışık","Genel",2,"Data was collected over successive generations."],
["Sufficient","Yeterli","Genel",1,"Sufficient evidence supports the theory."],
["Superficial","Yüzeysel","Genel",2,"The wound was superficial and healed quickly."],
["Supplement","Takviye/Ek","Biyoloji",1,"Vitamin supplements support immune function."],
["Supply","Tedarik/Sağlamak","Genel",1,"Blood vessels supply oxygen to tissues."],
["Suppress","Bastırmak/Baskılamak","Biyoloji",2,"The drug suppresses the immune response."],
["Surface","Yüzey","Fen",1,"The surface of Mars contains iron oxide."],
["Surge","Artış/Dalgalanma","Genel",2,"A surge in temperature was recorded."],
["Surplus","Fazla/Artık","Genel",2,"Surplus energy is stored as fat."],
["Surroundings","Çevre/Ortam","Genel",1,"Organisms interact with their surroundings."],
["Survive","Hayatta kalmak","Biyoloji",1,"Only the fittest organisms survive."],
["Susceptible","Duyarlı/Hassas","Biyoloji",2,"Young children are more susceptible to infections."],
["Suspend","Askıya almak","Kimya",2,"Particles were suspended in the liquid."],
["Sustain","Sürdürmek/Desteklemek","Genel",1,"The ecosystem cannot sustain this level of pollution."],
["Synthesis","Sentez","Kimya",2,"Protein synthesis occurs in ribosomes."],
["Tangible","Somut/Elle tutulur","Genel",2,"The benefits of the research are now tangible."],
["Technique","Teknik/Yöntem","Fen",1,"A new technique for gene editing was developed."],
["Temperature","Sıcaklık","Fizik",1,"Temperature affects the rate of chemical reactions."],
["Temporary","Geçici","Genel",1,"The effect of the drug is temporary."],
["Tendency","Eğilim","Genel",1,"There is a tendency for temperatures to rise."],
["Terminate","Sonlandırmak","Genel",2,"The reaction was terminated by cooling."],
["Terrain","Arazi/Zemin","Fen",1,"The terrain was rocky and unsuitable for farming."],
["Thesis","Tez","Genel",2,"The thesis was supported by experimental evidence."],
["Thorough","Kapsamlı/Titiz","Genel",2,"A thorough investigation was conducted."],
["Threshold","Eşik","Fen",2,"The pain threshold varies from person to person."],
["Tissue","Doku","Biyoloji",1,"Muscle tissue contracts during movement."],
["Toxic","Zehirli/Toksik","Kimya",1,"Mercury is a toxic heavy metal."],
["Trace","İz/İzlemek","Fen",1,"Trace amounts of the element were detected."],
["Trait","Özellik","Biyoloji",1,"Genetic traits are passed from parents to offspring."],
["Transfer","Aktarmak/Transfer","Fen",1,"Energy is transferred through heat conduction."],
["Transform","Dönüştürmek","Genel",1,"Caterpillars transform into butterflies."],
["Transition","Geçiş","Fen",2,"The transition from liquid to gas requires energy."],
["Transmit","İletmek/Aktarmak","Fen",1,"Nerves transmit signals to the brain."],
["Transparent","Saydam/Şeffaf","Fizik",1,"Glass is transparent to visible light."],
["Trend","Eğilim/Akım","Genel",1,"An upward trend in carbon emissions was noted."],
["Trigger","Tetiklemek","Fen",1,"Stress can trigger hormonal changes."],
["Trivial","Önemsiz","Genel",2,"The difference was trivial and ignored."],
["Tumor","Tümör","Biyoloji",1,"The tumor was removed through surgery."],
["Turbulent","Çalkantılı/Türbülanslı","Fizik",2,"Turbulent flow occurs at high velocities."],
["Ultimate","Nihai/Son","Genel",1,"The ultimate goal is to cure the disease."],
["Undergo","Geçirmek/Maruz kalmak","Genel",1,"Cells undergo division during growth."],
["Underlie","Altında yatmak","Genel",2,"Genetic factors underlie many diseases."],
["Undertake","Üstlenmek","Genel",2,"The institute undertook a five-year study."],
["Uniform","Tekdüze/Homojen","Fen",2,"The solution must be of uniform concentration."],
["Unique","Eşsiz/Benzersiz","Genel",1,"Each organism has a unique DNA sequence."],
["Utilize","Kullanmak/Yararlanmak","Genel",1,"Plants utilize sunlight for energy."],
["Valid","Geçerli","Genel",1,"The results are valid only under certain conditions."],
["Variable","Değişken","Fen",1,"Temperature was the independent variable."],
["Vary","Değişmek/Farklılık göstermek","Genel",1,"Results vary depending on the sample size."],
["Vegetation","Bitki örtüsü","Biyoloji",1,"Dense vegetation covers the valley floor."],
["Verify","Doğrulamak","Genel",1,"The findings were verified through replication."],
["Version","Versiyon/Sürüm","Genel",1,"A new version of the model was developed."],
["Vertical","Dikey","Fizik",1,"The vertical axis represents temperature."],
["Viable","Yaşayabilir/Uygulanabilir","Genel",2,"Nuclear fusion remains a viable energy option."],
["Vigorous","Güçlü/Şiddetli","Genel",2,"The reaction was vigorous and exothermic."],
["Virtual","Sanal","Genel",1,"Virtual simulations replace costly experiments."],
["Visible","Görünür","Fizik",1,"Visible light is only a part of the spectrum."],
["Vital","Hayati/Çok önemli","Genel",1,"Water is vital for all forms of life."],
["Volatile","Uçucu/Değişken","Kimya",2,"Volatile organic compounds evaporate quickly."],
["Volume","Hacim","Fizik",1,"The volume of the gas increased with temperature."],
["Vulnerable","Savunmasız/Hassas","Biyoloji",1,"Coral reefs are vulnerable to ocean acidification."],
["Wavelength","Dalga boyu","Fizik",2,"Different colors correspond to different wavelengths."],
["Whereas","Oysa/Halbuki","Genel",1,"Plants produce oxygen, whereas animals consume it."],
["Widespread","Yaygın","Genel",1,"Pollution is a widespread environmental problem."],
["Yield","Verim/Üretmek","Fen",1,"The experiment yielded unexpected results."],
["Zone","Bölge/Alan","Fen",1,"The intertidal zone supports diverse marine life."],
];
const existing = JSON.parse(fs.readFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json','utf8'));
const startId = existing.length + 1;
const words = raw.map((r, i) => ({
  id: startId + i, word_en: r[0], word_tr: r[1], category: r[2], difficulty: r[3], example_sentence: r[4]
}));
const all = [...existing, ...words];
fs.writeFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_merged.json', JSON.stringify(all, null, 2));
console.log(`Part 4: ${words.length} new. Total: ${all.length} words.`);
