const fs = require('fs');
// Format: [word_en, word_tr, category, difficulty, example_sentence]
const raw = [
["Absorb","Emmek/Soğurmak","Fen",1,"Plants absorb nutrients from the soil."],
["Accelerate","Hızlandırmak","Fizik",1,"Catalysts accelerate the chemical reaction."],
["Accumulate","Biriktirmek/Toplamak","Fen",1,"Toxins accumulate in the food chain over time."],
["Adapt","Uyum sağlamak","Biyoloji",1,"Species adapt to their environment through natural selection."],
["Adequate","Yeterli","Genel",1,"An adequate supply of oxygen is essential for survival."],
["Affect","Etkilemek","Genel",1,"Climate change affects biodiversity worldwide."],
["Aggregate","Toplamak/Kümelemek","Fen",2,"Data was aggregated from multiple research centers."],
["Allocate","Tahsis etmek","Genel",2,"Resources were allocated for the new experiment."],
["Alter","Değiştirmek","Genel",1,"Genetic engineering can alter the DNA of organisms."],
["Amplify","Yükseltmek/Güçlendirmek","Fizik",2,"The device amplifies weak electrical signals."],
["Analyze","Analiz etmek","Genel",1,"Scientists analyze data to draw conclusions."],
["Anticipate","Öngörmek/Tahmin etmek","Genel",2,"Researchers anticipate a rise in global temperatures."],
["Apparent","Açık/Belirgin","Genel",1,"The effects of pollution are apparent in coastal areas."],
["Approach","Yaklaşım/Yaklaşmak","Genel",1,"A new approach to cancer treatment has been developed."],
["Approximate","Yaklaşık","Genel",1,"The approximate age of the fossil is 3 million years."],
["Assess","Değerlendirmek","Genel",1,"The study assessed the impact of deforestation."],
["Attribute","Atfetmek/Nitelik","Genel",2,"The decline is attributed to habitat loss."],
["Beneficial","Faydalı/Yararlı","Genel",1,"Exercise is beneficial for cardiovascular health."],
["Bond","Bağ","Kimya",1,"A covalent bond involves sharing of electrons."],
["Capacity","Kapasite/Yeterlilik","Genel",1,"The battery has a limited storage capacity."],
["Catalyst","Katalizör","Kimya",2,"Enzymes act as biological catalysts."],
["Chronic","Kronik/Süreğen","Biyoloji",2,"Chronic exposure to radiation increases cancer risk."],
["Circulate","Dolaşmak/Dolaştırmak","Biyoloji",1,"Blood circulates through the body via arteries."],
["Classify","Sınıflandırmak","Fen",1,"Scientists classify organisms based on shared traits."],
["Coherent","Tutarlı/Bağdaşık","Genel",2,"The theory provides a coherent explanation."],
["Coincide","Aynı zamana denk gelmek","Genel",2,"The outbreak coincided with seasonal changes."],
["Collaborate","İşbirliği yapmak","Genel",2,"Researchers collaborate across disciplines."],
["Commence","Başlamak","Genel",2,"The experiment commenced at dawn."],
["Compact","Sıkışık/Yoğun","Fizik",1,"The material has a compact molecular structure."],
["Comparable","Karşılaştırılabilir","Genel",2,"The results are comparable to previous studies."],
["Compatible","Uyumlu","Fen",2,"The two systems are not compatible with each other."],
["Compensate","Telafi etmek","Genel",2,"The body compensates for blood loss."],
["Complex","Karmaşık","Genel",1,"Protein folding is a complex process."],
["Component","Bileşen","Fen",1,"Water is a key component of all living cells."],
["Compound","Bileşik","Kimya",1,"Water is a compound made of hydrogen and oxygen."],
["Comprehensive","Kapsamlı","Genel",2,"A comprehensive review of the literature was conducted."],
["Comprise","Kapsamak/İçermek","Genel",2,"The ecosystem comprises numerous species."],
["Conceive","Tasarlamak/Kavramak","Genel",3,"The concept was first conceived in the 1950s."],
["Concentrate","Yoğunlaştırmak","Kimya",1,"The solution was concentrated by evaporation."],
["Conclude","Sonuç çıkarmak","Genel",1,"The researchers concluded that the hypothesis was valid."],
["Conduct","Yürütmek/İletmek","Fen",1,"Metals conduct heat and electricity efficiently."],
["Confine","Sınırlandırmak","Genel",2,"The infection was confined to a small area."],
["Confirm","Doğrulamak","Genel",1,"The experiments confirmed the earlier findings."],
["Consecutive","Ardışık/Art arda","Genel",2,"Temperatures rose for five consecutive years."],
["Consequence","Sonuç","Genel",1,"Deforestation has severe environmental consequences."],
["Conserve","Korumak/Muhafaza etmek","Biyoloji",1,"Efforts to conserve endangered species are increasing."],
["Considerable","Önemli/Hatırı sayılır","Genel",1,"A considerable amount of energy was released."],
["Consistent","Tutarlı","Genel",1,"The data is consistent with the model predictions."],
["Constitute","Oluşturmak","Genel",2,"Oxygen constitutes about 21 percent of the atmosphere."],
["Constraint","Kısıtlama/Sınırlama","Genel",2,"Budget constraints limited the scope of the study."],
["Consume","Tüketmek","Genel",1,"Humans consume vast amounts of natural resources."],
["Contaminate","Kirletmek/Bulaştırmak","Kimya",2,"Industrial waste can contaminate groundwater."],
["Contribute","Katkıda bulunmak","Genel",1,"Greenhouse gases contribute to global warming."],
["Convert","Dönüştürmek","Fen",1,"Solar panels convert sunlight into electricity."],
["Corrode","Aşındırmak","Kimya",2,"Acid rain corrodes metal structures over time."],
["Correspond","Denk gelmek/Karşılık gelmek","Genel",2,"The results correspond to theoretical predictions."],
["Crucial","Çok önemli/Kritik","Genel",1,"Water is crucial for all forms of life."],
["Decline","Azalmak/Düşüş","Genel",1,"The population of polar bears has declined sharply."],
["Deficient","Eksik/Yetersiz","Biyoloji",2,"A diet deficient in vitamin C causes scurvy."],
["Degrade","Bozulmak/Ayrışmak","Kimya",2,"Plastics take centuries to degrade in nature."],
["Demonstrate","Göstermek/Kanıtlamak","Genel",1,"The experiment demonstrated the effect of gravity."],
["Denote","Belirtmek/İfade etmek","Genel",2,"The symbol H denotes hydrogen."],
["Deplete","Tüketmek/Azaltmak","Fen",2,"Overfishing depletes marine resources rapidly."],
["Derive","Türetmek/Elde etmek","Genel",2,"Many medicines are derived from natural plants."],
["Detect","Tespit etmek/Saptamak","Fen",1,"The sensor can detect tiny changes in temperature."],
["Deteriorate","Kötüleşmek/Bozulmak","Genel",2,"Air quality continues to deteriorate in urban areas."],
["Determine","Belirlemek/Saptamak","Genel",1,"Scientists determined the exact cause of the disease."],
["Device","Cihaz/Aygıt","Fen",1,"A new device for measuring blood pressure was invented."],
["Diminish","Azaltmak/Küçültmek","Genel",2,"The ozone layer has diminished significantly."],
["Discharge","Boşaltmak/Deşarj","Fizik",2,"The factory discharged pollutants into the river."],
["Discrete","Ayrık/Kesikli","Fen",2,"Matter exists in discrete units called atoms."],
["Dispose","Elden çıkarmak/Bertaraf etmek","Fen",2,"Hazardous waste must be disposed of properly."],
["Dissolve","Çözmek/Eritmek","Kimya",1,"Salt dissolves easily in water."],
["Distinct","Belirgin/Farklı","Genel",1,"The two species are genetically distinct."],
["Distort","Çarpıtmak/Bozmak","Fizik",2,"Heat can distort the shape of metal objects."],
["Distribute","Dağıtmak","Genel",1,"Nutrients are distributed throughout the body."],
["Diverse","Çeşitli/Farklı","Biyoloji",1,"Tropical forests contain diverse species."],
["Dominate","Hâkim olmak/Egemen olmak","Genel",2,"One species can dominate an entire ecosystem."],
["Drastic","Köklü/Şiddetli","Genel",2,"Drastic measures are needed to reduce emissions."],
["Duration","Süre","Genel",1,"The duration of the experiment was three weeks."],
["Dwell","İkamet etmek/Yaşamak","Biyoloji",2,"Many organisms dwell in the deep ocean."],
["Elaborate","Ayrıntılı/Detaylandırmak","Genel",2,"The researcher elaborated on the methodology."],
["Element","Element/Öğe","Kimya",1,"Carbon is an essential element for life."],
["Elevate","Yükseltmek","Genel",2,"Elevated temperatures accelerate chemical reactions."],
["Eliminate","Ortadan kaldırmak","Genel",1,"The treatment eliminates harmful bacteria."],
["Emerge","Ortaya çıkmak","Genel",1,"New species emerge through evolutionary processes."],
["Emit","Yaymak/Salmak","Fizik",1,"The sun emits light and heat energy."],
["Emphasize","Vurgulamak","Genel",1,"The report emphasizes the need for clean energy."],
["Enable","Olanak sağlamak","Genel",1,"Technology enables faster data processing."],
["Encounter","Karşılaşmak","Genel",1,"Researchers encountered unexpected results."],
["Endure","Dayanmak/Katlanmak","Genel",2,"Some bacteria can endure extreme temperatures."],
["Enhance","Geliştirmek/Artırmak","Genel",1,"The new formula enhances fuel efficiency."],
["Enormous","Çok büyük/Devasa","Genel",1,"The universe contains an enormous number of galaxies."],
["Ensure","Sağlamak/Garanti etmek","Genel",1,"Safety protocols ensure the well-being of participants."],
["Entropy","Entropi/Düzensizlik","Fizik",3,"Entropy in a closed system always increases."],
["Enzyme","Enzim","Biyoloji",1,"Enzymes catalyze biochemical reactions in cells."],
["Equilibrium","Denge","Kimya",2,"Chemical equilibrium occurs when reaction rates are equal."],
["Equivalent","Eşdeğer","Genel",1,"One kilogram is equivalent to 2.2 pounds."],
["Erode","Aşındırmak","Fen",2,"Wind and water erode rock formations over time."],
["Essential","Temel/Gerekli","Genel",1,"Vitamins are essential for healthy growth."],
["Establish","Kurmak/Ortaya koymak","Genel",1,"The link between smoking and cancer is well established."],
["Estimate","Tahmin etmek","Genel",1,"Scientists estimate the age of the Earth at 4.5 billion years."],
["Evaluate","Değerlendirmek","Genel",1,"The committee evaluated the research proposal."],
["Evaporate","Buharlaşmak","Kimya",1,"Water evaporates faster at higher temperatures."],
["Evident","Açık/Belli","Genel",1,"The impact of climate change is now evident."],
["Evolve","Evrimleşmek/Gelişmek","Biyoloji",1,"Species evolve over millions of years."],
];
const words = raw.map((r, i) => ({
  id: i + 1, word_en: r[0], word_tr: r[1], category: r[2], difficulty: r[3], example_sentence: r[4]
}));
fs.writeFileSync('/Users/fatihbaygul/Desktop/english/scripts/words_part1.json', JSON.stringify(words, null, 2));
console.log(`Part 1: ${words.length} words written.`);
